# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: lint
        name: Make lint
        stages: [commit]
        language: rust
        entry: make lint
      - id: doc
        name: Make doc
        stages: [commit]
        language: rust
        entry: make doc
      - id: check
        name: Make check
        stages: [commit]
        language: rust
        entry: make check
